import type { MatchCardDTO, Swipe } from './types';

// ─── Mock Match Cards (simulating the feed API response) ───

export const mockMatchCards: MatchCardDTO[] = [
  {
    matchId: 'match-001',
    status: 'active',
    importerOrg: {
      id: 'org-imp-001',
      name: 'Shanghai Trade Group',
      country: 'China',
      industry: 'Electronics & Components',
      companySize: 'Enterprise',
      website: 'https://shanghaitrade.example.com',
    },
    importerLocation: { city: 'Shanghai', region: 'East China', country: 'China' },
    importerProducts: [
      { hsCode: '8542.31', category: 'Integrated Circuits', description: 'Electronic ICs and microcontrollers' },
      { hsCode: '8517.12', category: 'Telecom Equipment', description: 'Smartphones and communication devices' },
    ],
    matchScore: 92,
    trustScore: 88,
    finalScore: 94,
    factors: {
      productFit: 95,
      geographyFit: 90,
      buyerActivity: 96,
      scaleFit: 90,
      marketTrend: 88,
      tradeFrequency: 92,
    },
    trustComponents: {
      registrationVerification: 95,
      tradeHistory: 90,
      documentationFidelity: 82,
      paymentBehavior: 85,
    },
    reasons: [
      { rank: 1, label: 'Strong product alignment', description: 'Buyer actively imports HS 8542 products matching your top export category with 95% fit.', factorType: 'productFit' },
      { rank: 2, label: 'High trade frequency', description: 'Buyer completed 47 import transactions in the last 6 months, indicating consistent demand.', factorType: 'tradeFrequency' },
      { rank: 3, label: 'Active market engagement', description: 'Recent RFQs and platform activity suggest immediate buying intent.', factorType: 'buyerActivity' },
    ],
    quantity: '50,000+ units/month',
    timeline: 'Immediate',
    lastActive: '2 hours ago',
  },
  {
    matchId: 'match-002',
    status: 'active',
    importerOrg: {
      id: 'org-imp-002',
      name: 'Gulf Import Solutions',
      country: 'UAE',
      industry: 'Textiles & Fabrics',
      companySize: 'Mid-market',
      website: 'https://gulfimport.example.com',
    },
    importerLocation: { city: 'Dubai', region: 'Middle East', country: 'UAE' },
    importerProducts: [
      { hsCode: '5208.21', category: 'Cotton Fabrics', description: 'Woven cotton textiles, bleached' },
      { hsCode: '6109.10', category: 'Knitted Apparel', description: 'T-shirts and singlets, knitted' },
    ],
    matchScore: 85,
    trustScore: 82,
    finalScore: 87,
    factors: {
      productFit: 85,
      geographyFit: 88,
      buyerActivity: 90,
      scaleFit: 85,
      marketTrend: 78,
      tradeFrequency: 80,
    },
    trustComponents: {
      registrationVerification: 88,
      tradeHistory: 82,
      documentationFidelity: 78,
      paymentBehavior: 80,
    },
    reasons: [
      { rank: 1, label: 'Regional demand surge', description: 'UAE textile imports grew 18% YoY, with this buyer expanding procurement.', factorType: 'geographyFit' },
      { rank: 2, label: 'Product category match', description: 'Buyer seeks HS 5208 cotton fabrics aligning with your primary exports.', factorType: 'productFit' },
      { rank: 3, label: 'Consistent buyer activity', description: 'Regular monthly RFQs and platform engagement in the last quarter.', factorType: 'buyerActivity' },
    ],
    quantity: '10,000-25,000 units/month',
    timeline: '2-4 weeks',
    lastActive: '1 hour ago',
  },
  {
    matchId: 'match-003',
    status: 'active',
    importerOrg: {
      id: 'org-imp-003',
      name: 'Brazilian Distribution Co',
      country: 'Brazil',
      industry: 'Consumer Goods',
      companySize: 'Mid-market',
    },
    importerLocation: { city: 'Sao Paulo', region: 'Southeast', country: 'Brazil' },
    importerProducts: [
      { hsCode: '3304.99', category: 'Beauty Products', description: 'Cosmetics and skincare products' },
      { hsCode: '3401.11', category: 'Soap & Wash', description: 'Toilet soap and organic cleansers' },
    ],
    matchScore: 79,
    trustScore: 76,
    finalScore: 82,
    factors: {
      productFit: 80,
      geographyFit: 75,
      buyerActivity: 88,
      scaleFit: 82,
      marketTrend: 72,
      tradeFrequency: 70,
    },
    trustComponents: {
      registrationVerification: 82,
      tradeHistory: 75,
      documentationFidelity: 70,
      paymentBehavior: 78,
    },
    reasons: [
      { rank: 1, label: 'Active buyer engagement', description: 'Buyer has submitted 12 RFQs this month across consumer goods categories.', factorType: 'buyerActivity' },
      { rank: 2, label: 'Scale compatibility', description: 'Order volumes align well with your production capacity and MOQ requirements.', factorType: 'scaleFit' },
      { rank: 3, label: 'Emerging market growth', description: 'Brazil consumer goods imports projected to grow 14% in 2026.', factorType: 'marketTrend' },
    ],
    quantity: '5,000-15,000 units/month',
    timeline: '1-2 months',
    lastActive: '30 minutes ago',
  },
  {
    matchId: 'match-004',
    status: 'active',
    importerOrg: {
      id: 'org-imp-004',
      name: 'India Trade Hub',
      country: 'India',
      industry: 'Industrial Equipment',
      companySize: 'SME',
    },
    importerLocation: { city: 'Mumbai', region: 'Maharashtra', country: 'India' },
    importerProducts: [
      { hsCode: '8428.33', category: 'Conveyor Equipment', description: 'Belt conveyors for industrial use' },
      { hsCode: '8481.80', category: 'Industrial Valves', description: 'Taps, cocks, valves and similar appliances' },
    ],
    matchScore: 74,
    trustScore: 70,
    finalScore: 78,
    factors: {
      productFit: 75,
      geographyFit: 70,
      buyerActivity: 85,
      scaleFit: 78,
      marketTrend: 68,
      tradeFrequency: 65,
    },
    trustComponents: {
      registrationVerification: 78,
      tradeHistory: 68,
      documentationFidelity: 65,
      paymentBehavior: 70,
    },
    reasons: [
      { rank: 1, label: 'High buyer activity', description: 'Active search patterns for industrial equipment in the past 2 weeks.', factorType: 'buyerActivity' },
      { rank: 2, label: 'Scale alignment', description: 'SME-sized orders matching your flexible fulfillment capabilities.', factorType: 'scaleFit' },
      { rank: 3, label: 'Product relevance', description: 'Buyer imports HS 8428 products with growing demand for automation.', factorType: 'productFit' },
    ],
    quantity: '2,000-8,000 units/month',
    timeline: '2-3 months',
    lastActive: '45 minutes ago',
  },
  {
    matchId: 'match-005',
    status: 'active',
    importerOrg: {
      id: 'org-imp-005',
      name: 'Nordic Supply Chain AS',
      country: 'Norway',
      industry: 'Sustainable Materials',
      companySize: 'Mid-market',
    },
    importerLocation: { city: 'Oslo', region: 'Scandinavia', country: 'Norway' },
    importerProducts: [
      { hsCode: '4407.11', category: 'Sustainable Timber', description: 'FSC-certified coniferous lumber' },
      { hsCode: '4418.20', category: 'Wood Products', description: 'Prefabricated building components' },
    ],
    matchScore: 88,
    trustScore: 91,
    finalScore: 90,
    factors: {
      productFit: 82,
      geographyFit: 85,
      buyerActivity: 92,
      scaleFit: 88,
      marketTrend: 94,
      tradeFrequency: 86,
    },
    trustComponents: {
      registrationVerification: 95,
      tradeHistory: 92,
      documentationFidelity: 88,
      paymentBehavior: 90,
    },
    reasons: [
      { rank: 1, label: 'Sustainability trend leader', description: 'Norway has the highest ESG adoption rate; buyer prioritizes certified sustainable supply chains.', factorType: 'marketTrend' },
      { rank: 2, label: 'Excellent trust profile', description: 'Top-tier verification, 92% trade history score, and strong payment track record.', factorType: 'tradeFrequency' },
      { rank: 3, label: 'Volume growth trajectory', description: 'Buyer increased import volumes by 26% QoQ, signaling expansion.', factorType: 'buyerActivity' },
    ],
    quantity: '20,000+ units/quarter',
    timeline: 'Ongoing',
    lastActive: '15 minutes ago',
  },
  {
    matchId: 'match-006',
    status: 'active',
    importerOrg: {
      id: 'org-imp-006',
      name: 'MedTech Distributors Kenya',
      country: 'Kenya',
      industry: 'Medical Devices',
      companySize: 'SME',
    },
    importerLocation: { city: 'Nairobi', region: 'East Africa', country: 'Kenya' },
    importerProducts: [
      { hsCode: '9018.19', category: 'Diagnostic Equipment', description: 'Electro-diagnostic apparatus' },
      { hsCode: '9018.90', category: 'Medical Instruments', description: 'Surgical and medical instruments' },
    ],
    matchScore: 76,
    trustScore: 72,
    finalScore: 79,
    factors: {
      productFit: 78,
      geographyFit: 68,
      buyerActivity: 82,
      scaleFit: 75,
      marketTrend: 90,
      tradeFrequency: 60,
    },
    trustComponents: {
      registrationVerification: 80,
      tradeHistory: 65,
      documentationFidelity: 72,
      paymentBehavior: 70,
    },
    reasons: [
      { rank: 1, label: 'Explosive market growth', description: 'African medical device market projected to grow 22% CAGR; Kenya is the regional hub.', factorType: 'marketTrend' },
      { rank: 2, label: 'Active procurement cycle', description: 'Buyer is in active tender process for Q2 2026 hospital supply contracts.', factorType: 'buyerActivity' },
      { rank: 3, label: 'Product category fit', description: 'HS 9018 products directly match your medical device export portfolio.', factorType: 'productFit' },
    ],
    quantity: '500-2,000 units/quarter',
    timeline: '1-3 months',
    lastActive: '3 hours ago',
  },
];

// Simulated local swipe state (in real app, this comes from DB)
export const mockSwipes: Swipe[] = [];

// ─── Mock Connections ───

import type { ConnectionRequest, ChatMessage, AppNotification } from './types';

export const mockConnections: ConnectionRequest[] = [
  {
    id: 'conn-001',
    matchId: 'match-001',
    exporterOrgId: 'org-exp-001',
    exporterOrgName: 'Your Company',
    importerOrgId: 'org-imp-001',
    importerOrgName: 'Shanghai Trade Group',
    importerCountry: 'China',
    importerIndustry: 'Electronics & Components',
    finalScore: 94,
    status: 'accepted',
    createdAt: '2026-02-15T10:00:00Z',
    respondedAt: '2026-02-15T14:30:00Z',
    note: 'Interested in discussing partnership for Q2 orders.',
  },
  {
    id: 'conn-002',
    matchId: 'match-005',
    exporterOrgId: 'org-exp-001',
    exporterOrgName: 'Your Company',
    importerOrgId: 'org-imp-005',
    importerOrgName: 'Nordic Supply Chain AS',
    importerCountry: 'Norway',
    importerIndustry: 'Sustainable Materials',
    finalScore: 90,
    status: 'pending',
    createdAt: '2026-02-18T09:00:00Z',
    note: 'Would love to explore sustainable timber supply partnership.',
  },
  {
    id: 'conn-003',
    matchId: 'match-002',
    exporterOrgId: 'org-exp-001',
    exporterOrgName: 'Your Company',
    importerOrgId: 'org-imp-002',
    importerOrgName: 'Gulf Import Solutions',
    importerCountry: 'UAE',
    importerIndustry: 'Textiles & Fabrics',
    finalScore: 87,
    status: 'declined',
    createdAt: '2026-02-14T08:00:00Z',
    respondedAt: '2026-02-16T11:00:00Z',
  },
];

// ─── Mock Chat Messages (only for accepted connections) ───

export const mockMessages: ChatMessage[] = [
  {
    id: 'msg-001',
    connectionId: 'conn-001',
    senderId: 'org-exp-001',
    senderName: 'Your Company',
    senderRole: 'exporter',
    content: 'Hi! Thanks for accepting our connection. We\'d love to discuss our electronic components for your Q2 supply needs.',
    createdAt: '2026-02-15T15:00:00Z',
    read: true,
  },
  {
    id: 'msg-002',
    connectionId: 'conn-001',
    senderId: 'org-imp-001',
    senderName: 'Shanghai Trade Group',
    senderRole: 'importer',
    content: 'Thank you for reaching out! We\'re currently sourcing ICs and microcontrollers. Can you share your product catalog and MOQ details?',
    createdAt: '2026-02-15T16:30:00Z',
    read: true,
  },
  {
    id: 'msg-003',
    connectionId: 'conn-001',
    senderId: 'org-exp-001',
    senderName: 'Your Company',
    senderRole: 'exporter',
    content: 'Absolutely! I\'ll send over our full catalog. Our MOQ starts at 5,000 units with volume discounts at 25k+ and 50k+.',
    createdAt: '2026-02-15T17:00:00Z',
    read: true,
  },
  {
    id: 'msg-004',
    connectionId: 'conn-001',
    senderId: 'org-imp-001',
    senderName: 'Shanghai Trade Group',
    senderRole: 'importer',
    content: 'Great, that aligns with our volume. What are your lead times for standard IC orders? We need delivery within 4 weeks.',
    createdAt: '2026-02-16T09:15:00Z',
    read: false,
  },
];

// ─── Mock Notifications ───

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-001',
    type: 'connection_accepted',
    title: 'Connection Accepted',
    description: 'Shanghai Trade Group accepted your connection request.',
    connectionId: 'conn-001',
    read: true,
    createdAt: '2026-02-15T14:30:00Z',
  },
  {
    id: 'notif-002',
    type: 'new_message',
    title: 'New Message',
    description: 'Shanghai Trade Group sent you a message.',
    connectionId: 'conn-001',
    read: false,
    createdAt: '2026-02-16T09:15:00Z',
  },
  {
    id: 'notif-003',
    type: 'connection_sent',
    title: 'Connection Sent',
    description: 'Your connection request to Nordic Supply Chain AS was sent.',
    connectionId: 'conn-002',
    read: true,
    createdAt: '2026-02-18T09:00:00Z',
  },
  {
    id: 'notif-004',
    type: 'connection_declined',
    title: 'Connection Declined',
    description: 'Gulf Import Solutions declined your connection request.',
    connectionId: 'conn-003',
    read: false,
    createdAt: '2026-02-16T11:00:00Z',
  },
];
